using System;
using System.Collections.Generic;
using System.Numerics;
using KspMcp.Parts;

namespace KspMcp.Craft;

public class CraftPartInstance
{
    public PartInfo Part { get; set; }
    public string Uid { get; set; }
    public string CraftPartName => Part.Name.Replace('_', '.');
    public string FullId => $"{CraftPartName}_{Uid}";
    public uint PersistentId { get; set; }
    public Vector3 Position { get; set; }
    public Quaternion Rotation { get; set; } = Quaternion.Identity;

    public CraftPartInstance? Parent { get; set; }
    public List<CraftPartInstance> Children { get; } = new();

    // Node connections: NodeId (e.g. "top", "bottom") -> (OtherPart, OtherNodeId)
    public Dictionary<string, (CraftPartInstance OtherPart, string OtherNodeId)> NodeConnections { get; } = new();

    public int IgnitionStage { get; set; } = -1;
    public int DecoupleStage { get; set; } = 0;
    public int StageIndex { get; set; } = -1;
    public int StageSequenceOrder { get; set; } = -1;
    public int SeparationIndex { get; set; } = -1;

    public string AutostrutMode { get; set; } = "Grandparent";
    public bool RigidAttachment { get; set; } = true;

    public CraftPartInstance(PartInfo part, string uid, uint persistentId)
    {
        Part = part;
        Uid = uid;
        PersistentId = persistentId;
    }
}

public class CraftVessel
{
    public string Name { get; set; } = "Ai_Rocket";
    public string Description { get; set; } = "Craft generated by KSP MCP Autonomous AI Driver";
    public string Version { get; set; } = "1.12.5";
    public string Type { get; set; } = "VAB";
    public string VesselType { get; set; } = "Ship";
    public uint PersistentId { get; set; } = 1000000001;

    public CraftPartInstance? RootPart { get; set; }
    public List<CraftPartInstance> Parts { get; } = new();

    public Vector3 Size
    {
        get
        {
            if (Parts.Count == 0) return Vector3.Zero;
            float minX = float.MaxValue, maxX = float.MinValue;
            float minY = float.MaxValue, maxY = float.MinValue;
            float minZ = float.MaxValue, maxZ = float.MinValue;

            foreach (var p in Parts)
            {
                minX = Math.Min(minX, p.Position.X - 0.6f);
                maxX = Math.Max(maxX, p.Position.X + 0.6f);
                minY = Math.Min(minY, p.Position.Y - 1.0f);
                maxY = Math.Max(maxY, p.Position.Y + 1.0f);
                minZ = Math.Min(minZ, p.Position.Z - 0.6f);
                maxZ = Math.Max(maxZ, p.Position.Z + 0.6f);
            }

            return new Vector3(maxX - minX, maxY - minY, maxZ - minZ);
        }
    }
}
