// speed_up.ks - Fast-forward to impact
@LAZYGLOBAL OFF.
IF SHIP:ALTITUDE > 20000 {
    SET KUNIVERSE:TIMEWARP:MODE TO "RAILS".
    SET KUNIVERSE:TIMEWARP:WARP TO 4.
} ELSE {
    SET KUNIVERSE:TIMEWARP:MODE TO "PHYSICS".
    SET KUNIVERSE:TIMEWARP:WARP TO 3.
}

UNTIL ALT:RADAR < 200 {
    PRINT "ALTITUDE: " + ROUND(ALT:RADAR) + "m | SPEED: " + ROUND(SHIP:VELOCITY:SURFACE:MAG) + " m/s" AT (0, 10).
    WAIT 0.1.
}
PRINT "IMPACT IMMINENT!".
